# Generated by Django 3.2.13 on 2023-04-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='sold',
            new_name='rent',
        ),
    ]
