# Generated by Django 3.2.13 on 2023-04-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rename_sold_rent_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='date',
        ),
    ]
