# Generated by Django 3.2.13 on 2023-04-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20230422_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='rent',
            new_name='sell',
        ),
    ]
