# Generated by Django 3.2.13 on 2023-04-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rename_rent_rent_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='sell',
            new_name='is_rent',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='user_id',
            new_name='user',
        ),
    ]
