# Generated by Django 3.2.13 on 2023-04-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20230422_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='user',
            new_name='user_id',
        ),
    ]
