# Generated by Django 3.2.13 on 2023-04-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user_id'),
        ('rent', '0006_auto_20230422_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
    ]
