# Generated by Django 3.2.13 on 2023-04-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user_id'),
        ('rent', '0009_alter_rent_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
    ]
