# Generated by Django 4.1.6 on 2023-03-20 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorites', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
