# Generated by Django 3.2.13 on 2023-04-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=8, upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
