# Generated by Django 3.2.13 on 2023-04-10 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
