# Generated by Django 3.2.13 on 2023-04-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorites',
        ),
    ]
